version: '3.7'
services:
  mapnik:
    image: tms/mapnik:1
    build:
      context: mapnik/
      dockerfile: Dockerfile
    networks:
      - tms-net
    depends_on:
      - db
      - mq
    volumes:
      - type: bind
        source: ./exchange
        target: /input
    ports:
      - "5000:5000"
    environment:
      - DBNAME=osm
      - PGHOST=db
      - PGPORT=5432
      - PGUSER=tms
      - RABBITMQ_HOST=mq
  mq:
    image: rabbitmq:3-alpine
    networks:
      - tms-net
    ports:
      - "127.0.0.1:5672:5672"
  db:
    image: tms/db:1
    build:
      context: db/
      dockerfile: Dockerfile
    networks:
      - tms-net
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - type: bind
        source: ./data
        target: /var/lib/postgresql/data
    environment:
      - PG_WORK_MEM
      - PG_MAINTENANCE_WORK_MEM

networks:
  tms-net:
    name: "tms-net"
    driver:  bridge
