version: '3.7'
services:
  db:
    restart: always
  mq:
    restart: always
  nginx:
    build:
      context: nginx/
    restart: always
    ports:
      - 80:80
    depends_on:
      - frontend
    volumes:
      - type: bind
        source: ./static
        target: /home/pyuser/static
        read_only: true
  frontend:
    build:
      context: frontend/
      dockerfile: Dockerfile.prod
    image: "tms/frontend:latest"
    command: bash -c "daphne -b 0.0.0.0 -p 8000 TerritoriumMapServerFrontend.asgi:application"
    restart: always
    expose:
      - 8000
    volumes:
      - type: bind
        source: ./static
        target: /home/pyuser/static
