version: '3.7'
services:
  mapnik:
    image: tms/mapnik:1
    build:
      context: mapnik/
      dockerfile: Dockerfile
    networks:
      - tms-net
    depends_on:
      - db
    volumes:
      - type: bind
        source: ./exchange
        target: /input
    ports:
      - "5000:5000"
    environment:
      - DBNAME=osm
      - PGHOST=db
      - PGPORT=5432
      - PGUSER=tms
  import:
    image: tms/osm2pgsql:1
    build:
      context: import/
      dockerfile: Dockerfile
    networks:
      - tms-net
    depends_on:
      - db
    volumes:
      - type: bind
        source: ./exchange
        target: /input
    environment:
      - DBNAME=osm
      - PGHOST=db
      - PGPORT=5432
      - PGUSER=tms
      # - OSM2PGSQL_DATAFILE=...
  style:
    image: tms/style:1
    build:
      context: style/
      dockerfile: Dockerfile
    volumes:
      - type: bind
        source: ./exchange
        target: /output
    environment:
      - STYLE=de
      - DBNAME=osm
      - PGHOST=db
      - PGPORT=5432
      - PGUSER=tms
  python-base:
    image: tms/python-base:slim
    build:
      context: shapefiles/
      dockerfile: Dockerfile.python-base
  shapefiles:
    image: tms/shapefiles:1
    build:
      context: shapefiles/
      dockerfile: Dockerfile
    volumes:
      - type: bind
        source: ./exchange
        target: /output
  db:
    image: tms/db:1
    build:
      context: db/
      dockerfile: Dockerfile
    networks:
      - tms-net
    ports:
      - "127.0.0.1:5432:5432"
    environment:
      - PG_WORK_MEM
      - PG_MAINTENANCE_WORK_MEM

networks:
  tms-net:
    name: "tms-net"
    driver:  bridge
