name: tms_import

services:
  import:
    image: localhost/tms/osm2pgsql:1
    build:
      context: import/
      dockerfile: Dockerfile
    depends_on:
      - geodb
    volumes:
      - type: bind
        source: ./exchange
        target: /input
    env_file:
      - frontend/.env
  style:
    image: localhost/tms/style:1
    build:
      context: style/
      dockerfile: Dockerfile
    volumes:
      - type: bind
        source: ./exchange
        target: /output
    env_file:
      - frontend/.env
  python-base:
    image: localhost/tms/python-base:slim
    build:
      context: transcript/
      dockerfile: Dockerfile.python-base
  shapefiles:
    image: localhost/tms/shapefiles:1
    depends_on:
      - python-base
      - geodb
    build:
      context: shapefiles/
      dockerfile: Dockerfile
    volumes:
      - type: bind
        source: ./exchange
        target: /output
    env_file:
      - frontend/.env
  transcript:
    image: localhost/tms/transcript:1
    build:
      context: transcript/
      dockerfile: Dockerfile
    ports:
      - "127.0.0.1:8033:8033"
