version: '3.7'
services:
  mq:
    image: rabbitmq:3-alpine
    ports:
      - "127.0.0.1:5672:5672"
    environment:
      - RABBITMQ_ERLANG_COOKIE='AYMNAPKRPCPJVPFYAJZX'
      - RABBITMQ_DEFAULT_USER=tms
      - RABBITMQ_DEFAULT_PASS=tms
  geodb:
    image: tms/db:1
    build:
      context: db/
      dockerfile: Dockerfile
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - type: bind
        source: ./geodata
        target: /var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=tms
      - POSTGRES_USER=tms
      - POSTGRES_DB=osm
      - PG_WORK_MEM
      - PG_MAINTENANCE_WORK_MEM
  db:
    image: postgres:12.2-alpine
    volumes:
      - type: bind
        source: ./data
        target: /var/lib/postgresql/data
    ports:
      - "127.0.0.1:5433:5432"
    environment:
      - POSTGRES_USER=tms
      - POSTGRES_PASSWORD=tms
      - POSTGRES_DB=tms_frontend_dev
  mapnik:
    image: tms/mapnik:1
    build:
      context: mapnik/
      dockerfile: Dockerfile
    depends_on:
      - geodb
      - mq
    volumes:
      - type: bind
        source: ./exchange
        target: /input
    command: node ./app.js
    ports:
      - "127.0.0.1:5000:5000"
    environment:
      - DBNAME=osm
      - PGHOST=geodb
      - PGPORT=5432
      - PGUSER=tms
      - PGPASSWORD=tms
      - RABBITMQ_HOST=mq
      - RABBITMQ_DEFAULT_USER=tms
      - RABBITMQ_DEFAULT_PASS=tms
  frontend:
    build:
      context: frontend/
    image: "tms/frontend:latest"
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "127.0.0.1:8000:8000"
    depends_on:
      - mq
      - db
      - mapnik
    volumes:
      - type: bind
        source: ./files
        target: /home/pyuser/files
