version: '3.9'
services:
  frontend:
    build:
      context: frontend/
      dockerfile: Dockerfile
    image: "tms/frontend:latest"
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    depends_on:
      - mq
      - db
    volumes:
      - type: bind
        source: ./frontend
        target: /home/pyuser
