name: tms_import

services:
  import:
    image: tms/osm2pgsql:1
    build:
      context: import/
      dockerfile: Dockerfile
    depends_on:
      - geodb
    volumes:
      - type: bind
        source: ./exchange
        target: /input
    env_file:
      - frontend/.env
  style:
    image: tms/style:1
    build:
      context: style/
      dockerfile: Dockerfile
    volumes:
      - type: bind
        source: ./exchange
        target: /output
    env_file:
      - frontend/.env
  python-base:
    image: tms/python-base:slim
    build:
      context: shapefiles/
      dockerfile: Dockerfile.python-base
  shapefiles:
    image: tms/shapefiles:1
    depends_on:
      - python-base
    build:
      context: shapefiles/
      dockerfile: Dockerfile
    volumes:
      - type: bind
        source: ./exchange
        target: /output
