apiVersion: v1
kind: Secret
metadata:
  name: tms-secrets
type: Opaque
stringData:
  POSTGRES_PASSWORD: "tms"
  PGPASSWORD: "tms"
  RABBITMQ_DEFAULT_PASS: "tms"
  RABBITMQ_ERLANG_COOKIE: "ERLANGCOOKIEERLANGCO"
  SECRET_KEY: "abc_change_key"
  EMAIL_URL: "smtp://user:password@localhost:25"