apiVersion: v1
kind: Pod
metadata:
  annotations:
    io.kubernetes.cri-o.SandboxID/db: 460f228bac1ea11032b9a5abf21d105b8095d82fe7d83a1a8c0ad99b364c37e0
    io.kubernetes.cri-o.SandboxID/frontend: 460f228bac1ea11032b9a5abf21d105b8095d82fe7d83a1a8c0ad99b364c37e0
    io.kubernetes.cri-o.SandboxID/geodb: 460f228bac1ea11032b9a5abf21d105b8095d82fe7d83a1a8c0ad99b364c37e0
    io.kubernetes.cri-o.SandboxID/mapnik: 460f228bac1ea11032b9a5abf21d105b8095d82fe7d83a1a8c0ad99b364c37e0
    io.kubernetes.cri-o.SandboxID/mq: 460f228bac1ea11032b9a5abf21d105b8095d82fe7d83a1a8c0ad99b364c37e0
    io.kubernetes.cri-o.SandboxID/nginx: 460f228bac1ea11032b9a5abf21d105b8095d82fe7d83a1a8c0ad99b364c37e0
    io.kubernetes.cri-o.SandboxID/pdfemitter: 460f228bac1ea11032b9a5abf21d105b8095d82fe7d83a1a8c0ad99b364c37e0
    io.kubernetes.cri-o.SandboxID/redis: 460f228bac1ea11032b9a5abf21d105b8095d82fe7d83a1a8c0ad99b364c37e0
  creationTimestamp: "2025-12-26T08:27:25Z"
  labels:
    app: tms
  name: tms
spec:
  containers:
    - args:
        - postgres
      env:
        - name: POSTGRES_DB
          value: "osm"
        - name: POSTGRES_USER
          value: "tms"
      envFrom:
        - configMapRef:
            name: tms-config
        - secretRef:
            name: tms-secrets
      image: localhost/tms/db:1
      name: geodb
      ports:
        - containerPort: 80
          hostPort: 80
        - containerPort: 443
          hostPort: 443
      volumeMounts:
        - mountPath: /var/lib/postgresql
          name: tms-geodb-pvc
    - args:
        - redis-server
      image: docker.io/library/redis:8-alpine
      name: redis
      volumeMounts:
        - mountPath: /data
          name: 69babc1beed2fd0565b8adf0c29f7223bfddeabacc599490e101a8102e14921c-pvc
    - args:
        - postgres
      env:
        - name: POSTGRES_DB
          value: "tms_frontend"
        - name: POSTGRES_USER
          value: "tms"
        - name: PGPORT
          value: "5433"
      envFrom:
        - secretRef:
            name: tms-secrets
      image: docker.io/library/postgres:18-alpine
      name: db
      volumeMounts:
        - mountPath: /var/lib/postgresql
          name: tms-db-pvc
    - args:
        - rabbitmq-server
      envFrom:
        - configMapRef:
            name: tms-config
        - secretRef:
            name: tms-secrets
      image: docker.io/library/rabbitmq:4-alpine
      name: mq
      volumeMounts:
        - mountPath: /var/lib/rabbitmq
          name: 0c32b09ef7e901de3778ec5e58e65a24249277fd9653e08718a959844b8c0a92-pvc
    - args:
        - nginx
        - -g
        - daemon off;
      image: localhost/tms/nginx:latest
      name: nginx
      volumeMounts:
        - mountPath: /home/nginx/static
          name: tms-static-pvc
          readOnly: true
        - mountPath: /home/nginx/files
          name: tms-files-pvc
          readOnly: true
    - image: localhost/tms/pdfemitter:1
      name: pdfemitter
      securityContext:
        runAsNonRoot: true
    - args:
        - bash
        - -c
        - uv run daphne -b 0.0.0.0 -p 8000 TerritoriumMapServerFrontend.asgi:application
      env:
        - name: DJANGO_SETTINGS_MODULE
          value: TerritoriumMapServerFrontend.settings
      envFrom:
        - configMapRef:
            name: tms-config
        - secretRef:
            name: tms-secrets
      image: localhost/tms/frontend:latest
      name: frontend
      securityContext: { }
      volumeMounts:
        - mountPath: /home/pyuser/static
          name: tms-static-pvc
        - mountPath: /input
          name: tms-exchange-pvc
        - mountPath: /home/pyuser/files
          name: tms-files-pvc
    - args:
        - /bin/bash
        - -c
        - bun run app.js
      env:
        - name: MAPNIK_PLUGIN_DIRECTORY
          value: /usr/local/lib/mapnik/input/
        - name: FONT_DIRECTORY
          value: /input/fonts
      envFrom:
        - configMapRef:
            name: tms-config
        - secretRef:
            name: tms-secrets
      image: localhost/tms/mapnik:1
      name: mapnik
      volumeMounts:
        - mountPath: /input
          name: tms-exchange-pvc
  volumes:
    - name: tms-db-pvc
      persistentVolumeClaim:
        claimName: tms-db
    - name: 0c32b09ef7e901de3778ec5e58e65a24249277fd9653e08718a959844b8c0a92-pvc
      persistentVolumeClaim:
        claimName: 0c32b09ef7e901de3778ec5e58e65a24249277fd9653e08718a959844b8c0a92
    - name: tms-static-pvc
      persistentVolumeClaim:
        claimName: tms-static
    - name: tms-files-pvc
      persistentVolumeClaim:
        claimName: tms-files
    - name: tms-exchange-pvc
      persistentVolumeClaim:
        claimName: tms-exchange
    - name: tms-geodb-pvc
      persistentVolumeClaim:
        claimName: tms-geodb
    - name: 69babc1beed2fd0565b8adf0c29f7223bfddeabacc599490e101a8102e14921c-pvc
      persistentVolumeClaim:
        claimName: 69babc1beed2fd0565b8adf0c29f7223bfddeabacc599490e101a8102e14921c
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: tms-config
data:
  STYLE: "de"
  LANGUAGES: "de:German,en:English"
  REDIS_URL: "redis://redis:6379/0"
  DATABASE_URL: "postgresql://tms:tms@db:5433/tms_frontend"
  GEO_DATABASE_URL: "postgis://tms:tms@geodb:5432/osm"
  RABBITMQ_URL: "amqp://tms:tms@mq:5672/%2F?connection_attempts=10&retry_delay=5.0"
  RABBITMQ_DEFAULT_USER: "tms"
  PGHOST: "geodb"
  PGPORT: 5432
  PDF_EMITTER_URL: "http://pdfemitter:8080"
  ALLOWED_HOSTS: "127.0.0.1,localhost,frontend"
  CSRF_TRUSTED_ORIGINS: "https://127.0.0.1,https://localhost,https://frontend"
  FONT_DIRECTORY: "/input/fonts/"
  MAX_POLYGONS: "9"
  DEFAULT_FROM_EMAIL: "webmaster@example.com"
  EMAIL_SEND_URL: "http://localhost:8000"
  OSM2PGSQL_CACHE: "512"
  OSM2PGSQL_NUMPROC: "1"
  DEBUG: "False"
  OSM2PGSQL_DATAFILE: "data.osm.pbf"
